config/routes.rb
Rails.application.routes.draw do
  # root 'pages#home'
  devise_for :users
  # root "home#index"
  # root 'pages#home'
  resources :likes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy]
  end

  root "users#index"
  # root to: "home#index" 



  resources :posts do
    resources :comments, only: [:create, :destroy, :new]
    resources :likes, only: [:create]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :author_id, presence: true
  validates :post_id, presence: true

  after_save :update_counter

  def update_counter
    post.increment(:comments_counter)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], author_id: current_user.id, post_id: @post.id)

    if @comment.save
      flash[:notice] = 'comment created successfully'
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Success!'
    else
      render :new, alert: 'Error occured!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy!
    redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Success!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text).tap do |comment_params|
      comment_params.require(:text)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_create.html.erb
<%= form_with model:[@post, @post.comments.new], method: :post, local: true do |f| %>
  <div class="form-group">
  <div class="form">
    <%= f.label :text, "Comment", class: "control-label" %>
  <div class="col-75">
    <%= f.text_area :text, size: "50x3", :placeholder => "Type your comment...", required: true%>
  </div>
  <%= f.submit "Submit", class: "btn-comment", data: {disable_with: "Loading..."} %>
  </div>
<% end %>
</div>

app/views/comments/new.html.erb
<%= form_with model:@comment, url: post_comments_path do |f| %>
  <div class="form-group">
  <div class="form">
    <%= f.label :text, "Comment", class: "control-label" %>
  <div class="col-75">
    <%= f.text_area :text, size: "50x3", :placeholder => "Type your comment...", required: true%>
  </div>
  <%= f.submit "Submit", class: "btn-comment", data: {disable_with: "Loading..."} %>
  </div>
<% end %>
</div>