config/routes.rb
Rails.application.routes.draw do
  # root 'pages#home'
  devise_for :users
  # root "home#index"
  # root 'pages#home'
  resources :likes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy]
  end

  root "users#index"
  # root to: "home#index" 



  resources :posts do
    resources :comments, only: [:create, :destroy, :new]
    resources :likes, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal_to: 0

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/users_controller.rb
module Api
  module V1
    include JsonWebToken
    class UsersController < ApiController
      before_action :authorize_request, except: :login
      def index
        users = User.all
        render json: { status: 'SUCCESS', message: 'Loaded users successfully', data: users }, status: :ok
      end

      def login
        @user = User.find_by_email(params[:email])
        if @user
          token = jwt_encode(user_id: @user.id)
          time = Time.now + 7.days.to_i
          render json: { token:, exp: time.strftime('%m-%d-%Y %H:%M'),
                         Name: @user.name }, status: :ok
        else
          render json: { error: 'unauthorized' }, status: :unauthorized
        end
      end

      private

      def login_params
        params.permit(:email, :password)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="users">
    <% if @users.blank? %>
        <p>There are not any posts currently in the system.</p>
    <% else %>
    <ul>
        <% @users.each do |user| %>
            <li class="user-list">
            <div class="user-details">
                <%# <%= image_tag("profile.jpg", :alt => "User icon") %> 
                <%= link_to user.name, user_path(user) %>
                <p>Number of posts: <span><%= user.posts.count %></span></p>
            </div>
            </li>
        <% end %>
    </ul>
    <% end %>
</section>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="user-details">
      <div class="user-profile-image">
          <%# <%= image_tag("profile.jpg", :alt => "User icon", width:'100px', height:'100px') %> 
      </div>
      <div class="user-profile-details">
          <h1><%= @user.name %></h1>
          <p>Number of posts: <span><%= @user.posts.count %></span></p>
      </div>
  </div>
  <% if @user.recent_posts.blank? %>
      <p><%= @user.name %> does not have any posts currently.</p>
  <% else %>
<div class="user-posts">
<% @user.recent_posts.each do |post| %>
  <div class="comment_col">
      <h2><%= link_to post.title, user_post_path(@user) %></h2>
      <p><%= post.text %></p>
      <h3>Comment <%= post.comments.count%>,  <span>Likes <%= post.likes.count%></span></h3>
  </div>
<%end%>
<% end %>
<button class="button"><span><%= link_to "All posts", user_posts_path(@user) %> </span></button>
</div>
</div>