config/routes.rb
Rails.application.routes.draw do
  # root 'pages#home'
  devise_for :users
  # root "home#index"
  # root 'pages#home'
  resources :likes
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy]
  end

  root "users#index"
  # root to: "home#index" 



  resources :posts do
    resources :comments, only: [:create, :destroy, :new]
    resources :likes, only: [:create]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, length: { in: 1..250 }, presence: true, allow_blank: false
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal_to: 0

  after_save :update_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController
      before_action :authorize_request

      def list_posts
        author_id = params[:user_id]
        if author_id
          posts = Post.where(author_id:)
          render json: { status: 'SUCCESS', message: 'Loaded posts successfully', data: posts }, status: :ok
        else
          render json: { status: 'ERROR', message: 'User posts not found' }, status: :not_found
        end
      end

      def list_comments
        author_id = params[:user_id]
        post_id = params[:post_id]
        if author_id && post_id
          comments = Comment.where(author_id:, post_id:)
          render json: { status: 'SUCCESS', message: 'Loaded comments successfully', data: comments },
                 status: :ok
        else
          render json: { status: 'ERROR', message: 'User or post not found' }, status: :not_found
        end
      end

      def add_comment
        author_id = @current_user.id
        text = params[:text]
        post_id = params[:post_id]
        if author_id && text && post_id
          comment = Comment.new(author_id:, text:, post_id:)
          if comment.save
            render json: { status: 'SUCCESS', message: 'Saved comment successfully', data: comment },
                   status: :ok
          else
            render json: { status: 'ERROR', message: 'Comment not saved', data: comment.errors },
                   status: :unprocessable_entity
          end
        else
          render json: { status: 'ERROR', message: 'Parameters incomplete' }, status: :not_found
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @current_person = @user
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])

    new_post = @user.posts.new(post_params)
    new_post.likes_counter = 0
    new_post.comments_counter = 0
    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to user_posts_path(params[:user_id]), notice: 'Post was successfully created.'
        else
          render :new, alert: 'Error occurred, please try again. Post not saved'
        end
      end
    end
  end

  def show
    @post = User.find(params, load_and_authorize_resource[:user_id]).posts.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(post.author_id)
    user.posts_counter -= 1
    post.destroy
    user.save
    flash[:alert] = 'You have successfully deleted the post!'
    redirect_to user_posts_path(post.author_id)
  end

  private

  def post_params
    params.require(:data).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="posts">
    <div class="user">
      <a class="link-to-user" href="/users/<%= @user.id %>"><%= @user.name %></a>
      <h4 class="posts-count">Posts(<%= @user.posts.size %>)</h4>
        <% if @user && @user.id == @user.id%>
     <%= link_to "New post", new_user_post_path(@user.id) %>
    <% end %>
    </div>
    <div class="carousel">
        <%= image_tag("profile-placeholder.png", :alt => "User icon", class: "placeholder") %>
    </div>
</div>
    <%= link_to "All Users", root_path, class: "all-users-link" %>
<div class="card"> 
    <div class="card-body">
    <% @posts.each do |post| %>
            <li><%= link_to post.title, {:action => 'show', :id => post.id}%></li>
            <p><%= post.text %></p>
            <h3>Comment <%= post.comments.count%>,  <span>Likes <%= post.likes.count%></span></h3>
            <div class="comments">
            <% post.recent_comments.each do |comment| %>
                <div class="comment">
                    <p><%= comment.text %></p>
                </div>
            <% end %>
             </div>
        <% end %>
        </div> 
</div>

app/views/posts/new.html.erb
<%= form_with url: user_posts_path, scope: :data do |form| %>
<div class="form-container d-flex">
	<section class="title-section from-input d-flex">
		<%= form.label :title, "Title", class: "label" %>
		<%= form.text_field :title, placeholder: "Title", required: true %>
	</section>
	<section class="body-section from-input d-flex">
		<%= form.text_area :text, placeholder: "Type here...", rows: 14, required: true %>
	</section>
	<%= form.submit "Post", class: "submit-btn" %>
  </div>
<% end %>

app/views/posts/post.html.erb
<h1 class ="post-create-header">Create a post</h1>
<%= form_with url: user_posts_path, scope: :data do |form| %>
<div class="form-container d-flex">
	<section class="title-section from-input d-flex">
		<%= form.label :title, "Title", class: "label" %>
		<%= form.text_field :title, placeholder: "Title", required: true %>
	</section>
	<section class="body-section from-input d-flex">
		<%= form.text_area :text, placeholder: "Type here...", rows: 14, required: true %>
	</section>
	<%= form.submit "Post", class: "submit-btn" %>
  </div>
<% end %>

app/views/posts/show.html.erb
 

<div class="card mb-3 p-4">
  <div class="card-body">
    <h5 class="card-title py-5 text-center fs-4"><%= @post.title %></h5>
    <title>By <%= @user %></title>
    <p class="card-text"><%= @post.text %></p>
    <p class="card-text"><small class="text-muted">Posted <%= time_ago_in_words(@post.created_at)%> ago</small></p>
    <div class="likes">
      <%= form_with model:[@post, @post.likes.new] do |f|%>
         <%= f.submit "Like", class: "likes-btn" %>
      <%end%>
      <strong>Likes: </strong><%= @post.likes.count %><br />
      <strong>Comments: </strong><%= @post.comments.count %><br />
      <strong><%= link_to "Add comment", new_post_comment_path(user_id: @post.author_id, post_id: @post.id ) %></strong><br />
      <%= button_to "Delete Post", user_post_path(user_id: @post.author_id, post_id: @post.id), method: :delete, class: 'btn btn-danger' if can? :destroy, @post %>
   </div>
  </div>
</div>
</div>

<% if @post.comments.blank? %>
<p class="text-center">There are no comments currently available.</p>
<% else %>
<div class="card border-success p-5 " >
  <div class="card-header bg-transparent border-success text-center">Comments</div>
  <div class="card-body">
  <% @post.comments.includes(:author).each do |comment| %>
    <div class="show-comment">
    <h4>
    <%= image_tag("profile.jpg", :alt => "User icon", :class => "avatar")%>
    <%= comment.author.name %>
    <%= button_to "Delete", post_comment_path(author_id: comment.author_id, post_id: comment.post_id,  id: comment.id), method: :delete, class: 'btn btn-danger btn-sm show-btn' if can? :destroy, comment %>
    </h4>
    <p class="card-text"><%= comment.text %></p>
    <p class="card-text"><small class="text-muted">Posted <%= time_ago_in_words(comment.created_at)%> ago</small></p>
   <% end %>
   </div>
  </div>
</div>
<% end %>